#!/bin/sh

TEMP=`getopt -o s:r: --long size,rate: -- "$@"`
eval set -- "$TEMP"

ARGS=""

while true
do
    case "$1" in
        -s|--size) ARGS="$ARGS-s $2 " ;;
        -r|--rate) ARGS="$ARGS-r $2 " ;;
        --) break ;;
    esac
    shift
done

# if there are arguments change the display
if [ ${#ARGS} -ne 0 ]
then
    # turn vsync off
    kill $(pgrep compton)
    # change the display settings
    xrandr $ARGS
    # turn vsync back on
    compton &
    # restart the background
    $HOME/.fehbg
fi

LINE=$(xrandr --query | grep \* )
RES=$(echo $LINE | grep -o -E [[:digit:]]*x[[:digit:]]*)
FPS=$(echo $LINE | grep -o -E [[:digit:]]+[[:punct:]][[:digit:]]+[[:punct:]] |\
        grep -o -E [[:digit:]]+[[:punct:]][[:digit:]]+)

echo "Display is currently $RES@$FPS""Hz"
