#!/bin/sh

TEMP=`getopt -o udm --long up,down,mute -- "$@"`
eval set -- "$TEMP"

while true
do
    case "$1" in
        -d|--down) amixer -D pulse set Master 2%- ;;
        -u|--down) amixer -D pulse set Master 2%+ ;;
        -m|--mute) amixer -D pulse set Master 1+ toggle ;;
        --) break ;;
    esac
    shift
done
