#!/bin/sh

OPTIND=1

while getopts dmu opt
do
    case "$opt" in
        d)
            amixer -D pulse set Master 2%-
            ;;
        u)
            amixer -D pulse set Master 2%+
            ;;
        m)
            amixer -D pulse set Master 1+ toggle
            ;;
        \?)
            exit 0
            ;;
    esac
done

shift $((OPTINID-1))
